### ISSUE TITLE
[PE-D][Tester D] App cannot check insanely big indexes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-3/tp#136]
When large indexes are used for the edit and delete command, it outputs that the name cannot be found, which might confuse the user to change the name instead. Maybe use long/big integer instead, or check for integers above a certain big number?

![Screenshot 2024-04-05 163129.png](https://raw.githubusercontent.com/alex-setyawan/ped/main/files/4cba5d3f-9a4c-4f49-a951-65275f7700ac.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: alex-setyawan/ped#5

**Comment by jonpwk** [comment]
Edit EditCommandParser to check for index < MAX_INT
