### ISSUE TITLE
[PE-D][Tester B] Tags Added Are Not Reflected In the UI Immediately

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-3/tp#93]
### Description:
Upon executing the `assign` command with the syntax `assign Bernice Yu t/neighbours`, the tags assigned to Bernice Yu are not promptly updated in the user interface (UI). These tags do not immediately reflect on Bernice Yu's contact box until the user clicks on one of the contact boxes. This delay in updating the tags within the UI disrupts the expected behavior and user experience.

![image.png](https://raw.githubusercontent.com/DhiraPT/ped/main/files/08e73425-cf09-4883-84f5-d126e1d2163b.png)

### Steps to Reproduce:
1. Execute the command `assign Bernice Yu t/neighbours`.
2. Observe that the contact box for Bernice Yu still does not have **neighbours** as one of the tags.
3. Click on one of the contact boxes in the list.
4. Observe that the contact box of Bernice Yu now includes **neighbours**.

### Expected Behavior:
After executing the `assign` command, the assigned tags should be promptly updated in the UI without requiring additional actions.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: DhiraPT/ped#3

**Comment by peienlim** [comment]
Same issue raised in #89
